[package]
name = "douglas_peucker"
version = "0.0.1"
authors = ["Denis Fomin <dfomin@retechlabs.com>"]
edition = "2018"

[lib]
name = "douglas_peucker"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.5"
num_cpus = "1.0"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]
